 -  name: install apache and php for ubuntu servers
    tags: apache,apache2,httpd
    apt:
       name:
         -  apache2
         -  libapache2-mod-php
       state:  latest
     when:  ansible_distribution ==  "Ubuntu"

  -  name:  install apache and php for centos servers
      tags:  apache,centos,httpd
      dnf:
        name:
          -httpd
          -php
        state:  latest
      when:  ansible_distribution ==  "CentOS"

   -  name:  start httpd  (centos)
      tags:  apache,centos,httpd
      service:
         name:  httpd
         state:  started
         enabled:  yes
      when: ansible_distribution ==  "CentOS"

   -  name: change e-mail address for admin
      tags: apache,centos,httpd
      lineinfile:
        path:  /etc/http/conf/httpd.conf
        regexp:  '^ServerAdmin'
        line:  ServerAdmin  somebody@somewhere.net
      when:  ansible_distribution  ==  "CentOS"
      register:  httpd
  -  name:  restart httpd  (CentOS)
     tags:  apache,centos,httpd
     service:
        name:  httpd
        state:  restarted
      when:  httpd.changed

   - name: copy default html file for site
     tags:  apache,apache2,httpd
     copy:
       src:  defat_site.html
       dest:  /var/www/html/index.html
       owner:  root
       group:  root
       mode:  0644
